### ISSUE TITLE
VS Code setup: tailwindcss-intellisense can't find executable

### ISSUE THREAD

**Issue by petrus-jvrensburg** [phoenixframework/tailwind#11]
Intellisense doesn't work for me in VS Code, because the https://github.com/tailwindlabs/tailwindcss-intellisense plugin can't find the _tailwindcss_ executable.

A workaround is to install a second executable locally, just for intellisense, via npm:

```
cd assets
npm install tailwindcss@3.0.7
npm install @tailwindcss/forms
rm package-lock.json
```

**Comment by ellismarkf** [comment]
I opened an issue with the `tailwindcss` team — this is really an issue for them, because the extension expects to find an executable in a particular place. Ideally it should be overridable by users in the extension settings. 

@petrus-jvrensburg your workaround is what I've done for now as well. 👍

**Comment by petrus-jvrensburg** [comment]
Yes, you're right. Thanks for logging that issue.
