### ISSUE TITLE
mix tailwind default - fails for tailwind 3.0.8

### ISSUE THREAD

**Issue by soullpoint** [phoenixframework/tailwind#13]
Attempting to run `mix tailwind default` after `mix tailwind.install` fails with the following error:

```
** (Mix) `mix tailwind default` exited with 137
```

Notably this only occurs for tailwind version 3.0.8. Changing the version back to 3.0.7 results in the `default` command running fine.

This was on a fresh project created using `mix phx.new my_project` and following the instructions on the readme. I was just seeing how the new tailwind integration works.

I am on macOS.

**Comment by holandes22** [comment]
@soullpoint are you using M1 architecture? issue #14 seems related.
I tried 3.0.8 on on my macOS (x86, Mojave) and it installed it ok for me

**Comment by soullpoint** [comment]
@holandes22 That's interesting, I am using an M1. Oddly enough I just tried it again just now and it seems to work now. Not sure what might have changed

**Comment by holandes22** [comment]
That is strange. Maybe there was an unrelated error or the correct binary for arm architecture was not downloaded the first time.

**Comment by chrismccord** [comment]
Closing since it is now reported as working. Please let us know if you have other issues. Thanks!
