### ISSUE TITLE
Can we support armv7 architecture?

### ISSUE THREAD

**Issue by thiagogsr** [phoenixframework/tailwind#29]
I'm trying to run a Phoenix project with Tailwind library in a raspberry but it is not working. The project is Dockerized, but when it runs `mix assets.deploy` it fails:

```
Step 16/24 : RUN mix assets.deploy
 ---> Running in 034ad1ec1be1

added 1 package, and audited 2 packages in 3s

found 0 vulnerabilities

22:38:37.140 [notice] Application tailwind exited: exited in: Tailwind.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) tailwind is not available for architecture: arm-unknown-linux-musleabihf
            (tailwind 0.1.5) lib/tailwind.ex:265: Tailwind.target/0
            (tailwind 0.1.5) lib/tailwind.ex:145: Tailwind.bin_path/0
            (tailwind 0.1.5) lib/tailwind.ex:162: Tailwind.bin_version/0
            (tailwind 0.1.5) lib/tailwind.ex:88: Tailwind.start/2
            (kernel 8.2) application_master.erl:293: :application_master.start_it_old/4
```

I'm using the `erlang:24.2.1-alpine` base image which is supports this platform.

**Comment by thiagogsr** [comment]
I see you rely on tailwind binaries, so it might be not possible at this moment, I'm closing this issue.

**Comment by prepor** [comment]
@thiagogsr is this still not possible? tailwind releases include a version for armv7 architecture https://github.com/tailwindlabs/tailwindcss/releases

**Comment by thiagogsr** [comment]
great to hear that @prepor , thanks

**Comment by prepor** [comment]
Can we reopen issue then? Do you have resources to support it or PR is welcome? ) I can create one, the only question is how to detect architecture. On my Raspberry Pi 3 I'm getting:

```
iex(8)>     arch_str = :erlang.system_info(:system_architecture)
'arm-unknown-linux-gnueabihf'
iex(9)>     [arch | _] = arch_str |> List.to_string() |> String.split("-")
["arm", "unknown", "linux", "gnueabihf"]
iex(10)> {:os.type(), arch, :erlang.system_info(:wordsize) * 8}
{{:unix, :linux}, "arm", 32}
```

I can add a mapping to `linux-armv7` for this triple and make a PR if you think it's valid.

**Comment by chrismccord** [comment]
If linux-armv7 is provided in the tailwind release, then yes please send a PR!

**Comment by thiagogsr** [comment]
Sure feel free to submit a PR @prepor
