### ISSUE TITLE
Specify multiple input files?

### ISSUE THREAD

**Issue by silverdr** [phoenixframework/tailwind#31]
Wondering if there's a way to specify more than one input file for bundling. Adding more than one `--input=…` doesn't seem to do the trick.

**Comment by chrismccord** [comment]
Not that I'm aware of. Thanks!

**Comment by ahasoftware** [comment]
The Tailwind CLI/exe doesn't support multiple outputs, however I wish this Elixir package could allow to define multiple config values and just run the CLI those X times.
