### ISSUE TITLE
Many `.gz` files in `priv/static/` end up being versioned by git

### ISSUE THREAD

**Issue by fdeage** [phoenixframework/tailwind#35]
Hi there, I've been using Tailwind for a while now and I think it's fantastic. It's great to see Tailwind adopted in an "official" package ^^

However, I noticed that, after installing it, I end up with a *lot* of files (`.gz` especially) versioned in my repo. Since these digested files are put in the same dir, and since only `priv/static/` is ignored, there are about 200 files popping when I do `git status`.

Is there a way to change the directory for digested assets, or maybe have git ignore the hashed files somehow?

**Comment by chrismccord** [comment]
```
You can use `mix phx.digest.clean` to prune stale versions of the assets.
If you want to remove all produced files, run `mix phx.digest.clean --all`.
```

**Comment by fdeage** [comment]
Thanks Chris! I guess it's part of the normal workflow then.
