### ISSUE TITLE
`mix tailwind default` exists with 137

### ISSUE THREAD

**Issue by JosephShering** [phoenixframework/tailwind#39]
Command:
`mix tailwind default`

Output:
`** (Mix) mix tailwind default exited with 137`

Platform:
Mac OS X (13-inch, M1, 2020)
Memory 16GB

Mix Tailwind Version:
`{:tailwind, "~> 0.1.5", runtime: Mix.env() == :dev}`

Mix Config Setup:
```elixir
config :tailwind,
  version: "3.0.10",
  default: [
    args: ~w(
      --config=tailwind.config.js
      --input=css/app.css
      --output=../priv/static/assets/app.css
    ),
    cd: Path.expand("../assets", __DIR__)
  ]
```

**Comment by chrismccord** [comment]
Can you try  bumping tailwind version to latest? (3.0.24) . I don't have an M1 architecture to test on, so hopefully the latest build will resolve whatever issues you're hitting

**Comment by JosephShering** [comment]
This is my new config entry:
```elixir
config :tailwind,
  version: "3.0.24",
  default: [
    args: ~w(
      --config=tailwind.config.js
      --input=css/app.css
      --output=../priv/static/assets/app.css
    ),
    cd: Path.expand("../assets", __DIR__)
  ]
```

Commands I ran:
`mix tailwind.install`

This is the output from the command:
`11:38:52.064 [debug] Downloading tailwind from https://github.com/tailwindlabs/tailwindcss/releases/download/v3.0.24/tailwindcss-macos-arm64`

Then I ran:
`mix tailwind default`

Output: 
`** (Mix) mix tailwind default exited with 137`

Are there any artifacts that I need to delete to ensure tailwind updates properly?

**Comment by chrismccord** [comment]
You could try invoking the standalone tailwinds cli directly from your `_build` dir and seeing if it provides more helpful output:

```
$ cd assets
$ ../_build/ailwindcss-macos-arm64 --config=tailwind.config.js --input=css/app.css --output=../priv/static/assets/app.css 
```

**Comment by JosephShering** [comment]
I ran:
`cd assets`

Then:
`../_build/tailwind-macos-arm64 --config=tailwind.config.js --input=css/app.css --output=../priv/static/assets/app.css`

This was the output:
`[1]    47934 killed     ../_build/tailwind-macos-arm64 --config=tailwind.config.js --input=css/app.css`

**Comment by cblock** [comment]
@JosephShering some over here on my M1

For me I managed to fix the problem by downloading the latest tailwindcss CLI ([as described here](https://tailwindcss.com/blog/standalone-cli)) and then I replaced  that binary with the (seemingly corrupted) Version at ```../_build/tailwind-macos-arm64```

**Comment by qborisb** [comment]
In my case, dropping the `_build` folder and running `mix tailwind.install` again helps

**Comment by dvic** [comment]
@chrismccord I have found out what is causing this problem: Mac OS seems to be killing the binary after you update the version. Simply deleting the binary inside `_build` and running `mix tailwind.install` resolves the problem. I think we should update the install script to first delete the file and then write a new file instead overwriting the current file: https://github.com/phoenixframework/tailwind/blob/b1d487608bc0486995772232c72961042ba15676/lib/tailwind.ex#L220

**Comment by shankardevy** [comment]
@JosephShering It looks like a typo in your issue title. It reads "exists" instead of "exited". can rename the title of this issue to "mix tailwind default exited with 137".

**Comment by dvic** [comment]
Does clearing the build folder or the tailwind binary in the build folder resolve the issue?

**Comment by dvic** [comment]
> @chrismccord I have found out what is causing this problem: Mac OS seems to be killing the binary after you update the version. This has to do with the signature of binary I think.
> 
> 
> 
> Simply deleting the binary inside `_build` and running `mix tailwind.install` resolves the problem. I think we should update the install script to first delete the file and then write a new file instead overwriting the current file: https://github.com/phoenixframework/tailwind/blob/b1d487608bc0486995772232c72961042ba15676/lib/tailwind.ex#L220
> 
> 
> 
> I can open a PR for this if you agree.

@chrismccord shall I submit a PR or is there some other (better) solution?
