### ISSUE TITLE
assets.deploy line replace or compliment existing?

### ISSUE THREAD

**Issue by ryanwinchester** [phoenixframework/tailwind#4]
In the readme, it says:

> make sure you have a `assets.deploy` alias for deployments, which will also use the `--minify` option:
> ```elixir
> "assets.deploy": ["tailwind default --minify", ..., "phx.digest"]
> ```

However, it's not entirely clear what it means in the context of an existing Phoenix project that already has an `assets.deploy` alias.

Does that mean we replace the existing one:

```diff
- "assets.deploy": ["esbuild default --minify", "phx.digest"]
+ "assets.deploy": ["tailwind default --minify", "phx.digest"]
```

Or that we update it to:

```diff
- "assets.deploy": ["esbuild default --minify", "phx.digest"]
+ "assets.deploy": ["tailwind default --minify", "esbuild default --minify", "phx.digest"]
```

**Comment by rowofpixels** [comment]
You keep esbuild there if you want to keep using it for your javascript. So for me I have:

```
"assets.deploy": ["tailwind default --minify", "esbuild default --minify", "phx.digest"]
```

**Comment by foucist** [comment]
That doesn't seem to be correct? tailwind.config.js has:
```
module.exports = {
  content: [
    './js/**/*.js',
```

 This works fine for me, and app.js still shows up
```
"assets.deploy": ["tailwind default --minify", "phx.digest"]
```
