### ISSUE TITLE
Automatically sort tailwind CSS classes

### ISSUE THREAD

**Issue by nelsonmestevao** [phoenixframework/tailwind#42]
The team behind Tailwind CSS, launched a [Prettier](https://prettier.io/) plugin for Tailwind CSS v3.0+ that automatically sorts classes based on [their recommended class order](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted).

I was thinking it would be really cool to be able to do the same by creating a [Mix Format Plugin](https://hexdocs.pm/mix/main/Mix.Tasks.Format.html#module-plugins) similar to what have been done to [HEEX](https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/html_formatter.ex) in Phoenix LiveView.

I am willing to work on this. Do you guys think it could be part of this package?

**Comment by lobo-tuerto** [comment]
I think this is fundamental for having a great DX while using Tailwind CSS.

**Comment by cgarvis** [comment]
https://github.com/100phlecs/tailwind_formatter

**Comment by nelsonmestevao** [comment]
Would @100phlecs be willing to merge is work in this project? Are the maintainers of this project willing to have this feature?

**Comment by josevalim** [comment]
Closing as it is out of scope for this project. Our focus is exclusively on the installer. :)
