### ISSUE TITLE
Install Creates "app.css"

### ISSUE THREAD

**Issue by morinap** [phoenixframework/tailwind#44]
Running a `mix tailwind.install` as part of my normal build process on my development environment automatically creates a file at `/assets/css/app.css`.  My project uses DartSass and has an `app.scss` file instead, so the net effect is that if I run my build from a clean working copy, I end up with an untracked file in git for `app.css`.

I propose adding a `--skip-prepare` option to the tailwind install task that will skip the modifications it makes to `app.css` and `app.js` if the user desires and have prepared a Pull Request for this functionality.

**Comment by josevalim** [comment]
I added --no-assets to disable the assets generation. :)
