### ISSUE TITLE
Dangling tailwind watcher process

### ISSUE THREAD

**Issue by anotherzxx** [phoenixframework/tailwind#46]
Esbuild watcher process `esbuild-darwin-arm64` will be terminated normally after `mix phx.server` stopped. While tailwind watcher process `tailwind-macos-arm64` survived, and its parent process became null. I thought it is kind of unexpected.

```
Erlang/OTP 25 [erts-13.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.13.4 (compiled with Erlang/OTP 24)

{:phoenix, "~> 1.6.10"}
```

**Comment by natrys** [comment]
Btw, this was fixed in tailwind v3.2.0 so can be closed
