### ISSUE TITLE
Installation always replaces the tailwind config

### ISSUE THREAD

**Issue by rowofpixels** [phoenixframework/tailwind#5]
Currently the installation process always replaces the tailwind config. So in CI for example since tailwind isn't there in `_build` the config gets replaced. I made a change on my own branch to only replace when the file does not exist: https://github.com/rowofpixels/tailwind/commit/5c1ca1da76eeb03b2f975699a3a6901411d06ade

The alternative in CI would be to:
- Run `mix tailwind.install`
- Modify the replaced config by using a separate file and replacing it again
- Run `mix assets.deploy`

Wondering which approach would be best.

**Comment by aj-foster** [comment]
As a workaround, I've renamed my custom configuration file to `tw.config.js` and modified my `config.exs` to have:

```elixir
config :tailwind,
  version: "3.0.7",
  default: [
    args: ~w(
      --config=tw.config.js
      --input=css/app.css
      --output=../priv/static/css/app-tw.css
    ),
    cd: Path.expand("../assets", __DIR__)
```

In CI, the installation still generates a `tailwind.config.js` file, but it is ignored during asset creation.

Not sure if it aligns with the goals of the maintainers, but I'd encourage you to open a PR with your changes from rowofpixels@5c1ca1d. Checking for existence prior to writing sounds like a good default behavior to me. 🙂 

If you happen to use a CI workflow with dependency installation + caching in a separate step/job, it may also be possible to run `mix tailwind.install` in the same step as `mix deps.get` and `mix deps.compile`. Later, when running the asset deploy in a different step/job, the tailwind executable will already be present.
