### ISSUE TITLE
Custom binary download

### ISSUE THREAD

**Issue by paridin** [phoenixframework/tailwind#59]
Is it possible to support the download for custom binaries?

My use case is downloading a custom tailwind binary that supports third-party plugin's ex. Daisy UI. 

We can use the Tailwind config to override the default binary URL to get the custom.

It shouldn't be a critical change.

**Comment by petermm** [comment]
this would be great to have, it's VERY easy to compile your own tailwind-cli with plugins included (namely [daisyui](https://daisyui.com))

**Comment by josevalim** [comment]
Closing in favor of #60.
