### ISSUE TITLE
Handling the vagueness of installing tailwind

### ISSUE THREAD

**Issue by Morzaram** [phoenixframework/tailwind#72]
Hey everyone. I was running into this issue where I create a new phoenix project and I start it up, and it leaves me with a non-formatted screen. I looked at the console and the phoenix logs, which says app.css cannot be found. Well, the reason is, is because it's still downloading the 44MB Tailwind binary. 
![image](https://user-images.githubusercontent.com/70202379/211219247-b567371a-d1f9-4ce4-9dd7-b0bda2f9ed42.png)
![image](https://user-images.githubusercontent.com/70202379/211219232-fbff8d4a-541a-47db-8d9d-afe498dd6291.png)

Now I know that we have a blue info line saying that it's downloading tailwind, but I thought because it moved to the next line, it was done. Turns out that's not the case. Also, there's no notifier on when it is downloaded.

![image](https://user-images.githubusercontent.com/70202379/211219009-14315d5b-dcf2-43de-a8fb-0490156ea1f0.png)

While I know this now, this can be a problem for newbies needing clarification, and others not used to this situation. 

So I wanted to fix it but not sure of the best approach. 2 ideas:

1. Have a progress bar for the download. It takes a bit of time because GitHub caps download to around 500kb/s (at least for me)
2. Have a more detailed warning saying, "until this says it's complete, your Tailwind CSS will not be compiled," and then whenever it is complete, it will say something like "Tailwind installed and ready to go please do these next steps"

Anyways, would love the feedback on this and hope to contribute!

**Comment by josevalim** [comment]
This has been address in Phoenix main. `mix phx.new` will now pre-install tailwind and we will also download it on `mix setup`.
