### ISSUE TITLE
install fails with empty http_proxy env-var

### ISSUE THREAD

**Issue by milahu** [phoenixframework/tailwind#73]
https://github.com/phoenixframework/tailwind/blob/5e0e7981bf17b13ded961c96886c4a665e0b3d27/lib/tailwind.ex#L304

see https://github.com/dwyl/phoenix-liveview-counter-tutorial/issues/114

**Comment by allenwyma** [comment]
I was having this issue when building using the default container from phoenix, I updated this line and it's building now: 

```
# compile assets
RUN unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy && mix assets.deploy
```
