### ISSUE TITLE
tailwind.install task does not honor profiles

### ISSUE THREAD

**Issue by cjbottaro** [phoenixframework/tailwind#77]
It's hardcoded to create `assets/tailwind.config.js` and `assets/css/app.css`, despite using profiles that use other directories.

Edit: `tailwind.install` is being invoked from my watcher config like this:
```
tailwind: {Tailwind, :install_and_run, [:engineering, ~w(--watch)]}
```

I think `run` uses the profile, but `install` doesn't.

Related to  #44.

**Comment by josevalim** [comment]
I added a --no-assets option so you can skip the assets.
