### ISSUE TITLE
Files created in root for umbrella projects

### ISSUE THREAD

**Issue by danschultzer** [phoenixframework/tailwind#79]
From https://github.com/phoenixframework/tailwind/issues/33#issuecomment-1225921916, we still see this issue constantly.

In umbrella projects tailwind generate sassets files in root when installing. It's very easy to reproduce. Just remove the tailwind bin file and Tailwind library will create assets files in root. This would also be an issue if you are using non-standard path for assets for whatever reason.

I opened a PR half a year ago to not auto generate files when watching the assets: https://github.com/phoenixframework/tailwind/pull/53

But maybe it's better to just deal with it using the `:cd` config: https://github.com/phoenixframework/tailwind/pull/78

**Comment by josevalim** [comment]
I added --no-assets to disable the assets generation. :)
